### ISSUE TITLE
Rename modid.mixins.json

### ISSUE THREAD

**Issue by kalinzange** [Derican/infinite-lava-fabric#2]
leaving the mixin config as this value can cause crashes with other mods that do the same. modid should be replaced with your mod id.

```
Uncaught exception in thread "main"
java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods infinitelava and scaffoldforever
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by Derican** [comment]
Oh, probably it is caused by undeleted assets/modid folder. I've figured out and uploaded 1.0.1. Thanks and have a try!
